# Actividad Semana 1 - Python y NumPy
### Predictive Analytics

**Instrucciones:**
- Resuelve cada pregunta en las celdas indicadas
- Usa f-strings para formatear la salida
- Agrega comentarios explicando tu logica
- Sube tu notebook completado al aula virtual

**Consideraciones:**
1. El codigo ejecuta correctamente y produce el resultado esperado.
2. Usa las funciones/metodos apropiados (ej: f-strings, list comprehension, funciones NumPy).
3. Codigo limpio con comentarios, variables con nombres descriptivos.

---
## Nivel Basico

### Pregunta 1: Listas y Aleatorios

Crear una lista llamada `lst_numeros` con 300 numeros aleatorios entre 100 y 600.
Luego:
1. Muestra el 25% de los primeros numeros generados (usa indexacion de listas)
2. Muestra cuantos numeros son mayores a 400
3. Muestra el valor maximo y minimo de la lista

**Tip:** Usa `random.randint()` o list comprehension con `random`

In [1]:
import random

random.seed(42)  # Para reproducibilidad

# Tu codigo aqui
lst_numeros = [random.randint(100, 600) for _ in range(300)]

# Muestra el 25% de los primeros elementos de la lista utilizando slicing y convirtiendo el resultado a entero 
# utilizando la función int() para obtener el índice correcto

lst_mod = lst_numeros[:int(len(lst_numeros) * 0.25)]

# Filtra aquellos numeros mayores a 400 utilizando una comprensión de listas

lst_mayores = [numero for numero in lst_numeros if numero > 400]

# Crea una lista con el número máximo y mínimo de la lista original utilizando las funciones max() y min()
lst_mayor_min = [max(lst_numeros), min(lst_numeros)]

print("Mostrar 25% de los primeros elementos:", lst_mod)
print("Cantidad de numeros mayores a 400:", len(lst_mayores))
print("Número máximo y mínimo:", lst_mayor_min)

Mostrar 25% de los primeros elementos: [427, 157, 112, 479, 240, 225, 214, 171, 477, 152, 446, 479, 556, 379, 144, 402, 316, 116, 115, 147, 211, 219, 358, 408, 113, 387, 201, 466, 432, 459, 379, 314, 212, 329, 401, 242, 514, 545, 103, 488, 512, 181, 457, 316, 274, 242, 179, 210, 590, 490, 272, 152, 147, 294, 149, 283, 533, 276, 409, 235, 513, 122, 473, 335, 374, 163, 598, 572, 293, 140, 382, 250, 524, 421, 416]
Cantidad de numeros mayores a 400: 124
Número máximo y mínimo: [600, 100]


### Pregunta 2: Funciones y Formula Cuadratica

Crea una **funcion** llamada `formula_cuadratica(a, b, c)` que retorne las dos raices de la ecuacion cuadratica:

$$x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

Pruebala con: `a=4, b=9, c=3`

**Bonus:** Agrega validacion para el caso donde el discriminante es negativo (raices complejas)

In [ ]:
# Tu codigo aqui
def formula_cuadratica(a,b,c):

    # Calcula el discriminante
    discriminante = b**2 - 4*a*c

    #Valida el discriminante para determinar el número de soluciones reales
    if discriminante < 0:
        return "No hay soluciones reales"
    elif discriminante == 0:
        x = -b / (2*a)
        return f"Una solución real: x = {x}"
    else:
        x1 = (-b + discriminante**0.5) / (2*a)
        x2 = (-b - discriminante**0.5) / (2*a)
        return f"Dos soluciones reales: x1 = {x1}, x2 = {x2}"
    

print(formula_cuadratica(4, 9, 3))      

### Pregunta 3: Markdown y LaTeX en Jupyter

En las celdas siguientes, practica escribiendo en Markdown:
1. Crea un titulo (H2) y un subtitulo (H3)
2. Escribe una lista ordenada con 3 elementos
3. Escribe una lista NO ordenada con 3 elementos
4. Crea una tabla con 3 columnas y 3 filas
5. Escribe las siguientes formulas en LaTeX:
   - Media: $\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i$
   - Desviacion estandar: $\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2}$

**Tu respuesta Markdown aqui (doble click para editar):**

1
## Markdown y Latex
#### Jupyter

2 Lista ordenada de elementos

1. Elemento A
2. Elemento B
3. Elemento C

3 Lista no ordenada de elementos

- Elemento no ordenado A
- Elemento no ordenado B
- Elemento no ordenado C

4
| Columna 1 | Columna 2 | Columna 3 |
|   ----------|----------|----------|
|  Item 1   |  Item 1   |  Item 1   |
|  Item 2   |  Item 2   |  Item 2   |
|  Item 3   |  Item 3   |  Item 3   |

5
Media: $\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i$ 

Desviacion estandar: $\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2}$


### Pregunta 4: List Comprehension

Dada la siguiente lista de temperaturas en Celsius:
```python
celsius = [0, 10, 20, 25, 30, 35, 40]
```

Usando **list comprehension**:
1. Convierte todas las temperaturas a Fahrenheit: `F = C * 9/5 + 32`
2. Filtra solo las temperaturas en Celsius mayores a 25
3. Crea una lista de tuplas `(celsius, fahrenheit)` para cada temperatura

In [8]:
celsius = [0, 10, 20, 25, 30, 35, 40]

# Tu codigo aqui
farenheit = [int(((temp * 1.8) + 32)) for temp in celsius]
filtrar_temp = [temp for temp in celsius if temp > 25]

tupla_celsius = tuple(celsius)
tupla_farenheit = tuple(farenheit)

print("Temperaturas en Farenheit:", farenheit)
print("Temperaturas mayores a 25°C:", filtrar_temp)

print ("Tupla de Celsius:", tupla_celsius)
print ("Tupla de Farenheit:", tupla_farenheit)

print (tupla_celsius + tupla_farenheit)


Temperaturas en Farenheit: [32, 50, 68, 77, 86, 95, 104]
Temperaturas mayores a 25°C: [30, 35, 40]
Tupla de Celsius: (0, 10, 20, 25, 30, 35, 40)
Tupla de Farenheit: (32, 50, 68, 77, 86, 95, 104)
(0, 10, 20, 25, 30, 35, 40, 32, 50, 68, 77, 86, 95, 104)


### Pregunta 5: Funciones Lambda + Map

Dada la siguiente lista de precios en dolares:
```python
precios_usd = [10.5, 25.0, 8.75, 42.0, 15.3]
```

1. Usa `map` con una funcion `lambda` para convertir todos los precios a soles (tipo de cambio = 3.75)
2. Usa `filter` con `lambda` para obtener solo los precios en soles mayores a 50
3. Muestra los resultados con f-strings formateados a 2 decimales

In [9]:
precios_usd = [10.5, 25.0, 8.75, 42.0, 15.3]

# Tu codigo aqui
# FUNCION QUE SE ENCARGA DE REDONDEAR LOS PRECIOS A 2 DECIMALES DE LAS LISTAS
def redondearListas(lista):
    return list(map(lambda precio: round(precio, 2), lista))

# Convierte los precios de USD a PEN utilizando map() y una función lambda que multiplica cada precio por 3.75
#map devuelve un objeto iterable, por lo que se convierte a una lista utilizando list() para obtener los precios en PEN como una lista.
#1
precios_pen = list(map(lambda precio: precio * 3.75, precios_usd))
#2
precios_mayores_50 = list(filter(lambda precio: precio > 50, precios_pen))
#3
precios_redondeados = redondearListas(precios_pen)
precios_redondeados2 = redondearListas(precios_mayores_50)

print (f"Precios en PEN: {precios_redondeados}")
print (f"Precios mayores a 50 PEN: {precios_redondeados2}")

Precios en PEN: [39.38, 93.75, 32.81, 157.5, 57.38]
Precios mayores a 50 PEN: [93.75, 157.5, 57.38]


---
## Nivel Intermedio

### Pregunta 6: Estadisticos con NumPy

Genera datos simulados de 100 estudiantes:
- `horas_estudio`: enteros aleatorios entre 1 y 12
- `notas`: numeros aleatorios con distribucion normal, media=14, desviacion=3

Usa `np.random.seed(42)` para reproducibilidad.

Luego calcula:
1. Media, mediana y desviacion estandar de ambas variables
2. El coeficiente de correlacion entre horas_estudio y notas
3. Cuantos estudiantes tienen nota >= 11 (aprobados)
4. El promedio de horas de estudio de los aprobados vs los desaprobados

Muestra todos los resultados con f-strings.

In [10]:
import numpy as np
np.random.seed(42)

# Tu codigo aqui
horas_estudio = np.random.randint(1, 12, 100)
notas = np.random.normal(loc=14, scale=3, size=100)

# Calcula la media, mediana y desviación estándar de ambas listas

mediana = np.median(horas_estudio)
media = np.mean(horas_estudio)
desviacion_estandar = np.std(horas_estudio)

# Coeficiente de correlación entre horas de estudio y notas 

coef = np.corrcoef(horas_estudio, notas)[0, 1]
print(coef)

#Saber cuantos estudiantes tienen nota mayor o igual a 11

estudiantes_aprobados = np.sum(notas >= 11)
print(f"Cantidad de estudiantes con nota mayor o igual a 11: {estudiantes_aprobados}")

#PROMEDIO DE HORAS DE ESTUDIO DE LOS ESTUDIANTES APROBADOS Y DESAPROBADOS

horas_aprobados = horas_estudio[notas >= 11]
horas_desaprobados = horas_estudio[notas < 11]

promedio_horas_aprobados = np.mean(horas_aprobados)
promedio_horas_desaprobados = np.mean(horas_desaprobados)

print(f"Promedio de horas de estudio de estudiantes aprobados: {promedio_horas_aprobados}")
print(f"Promedio de horas de estudio de estudiantes desaprobados: {promedio_horas_desaprobados}")

0.09212042364642174
Cantidad de estudiantes con nota mayor o igual a 11: 84
Promedio de horas de estudio de estudiantes aprobados: 6.238095238095238
Promedio de horas de estudio de estudiantes desaprobados: 5.25


### Pregunta 7: Manipulacion de Arrays

1. Crea un array de 60 numeros equidistantes entre 0 y 100 usando `np.linspace`
2. Reorganizalo en una matriz de 10 filas x 6 columnas con `reshape`
3. Muestra la forma del array resultante
4. Calcula el promedio de cada columna (usa `axis=0`)
5. Calcula el promedio de cada fila (usa `axis=1`)
6. Selecciona las filas donde el valor de la primera columna es mayor a 50
7. Transpone la matriz y muestra su nueva forma

In [11]:
import numpy as np

# Tu codigo aqui
def convertir_2_decimales(array):
    return np.round(array, 2)

#1 
array = np.linspace(start=0, stop=100, num=60)
print("Array con 2 decimales:", convertir_2_decimales(array))

#2
matriz = array.reshape(10,6)

#3
print("Matriz de 10 filas y 6 columnas:", convertir_2_decimales(matriz))

#4
calculo_prom_columna = np.mean(matriz, axis=0)
print("Promedio de cada columna:", convertir_2_decimales(calculo_prom_columna))

#5
calculo_prom_fila = np.mean(matriz, axis=1)
print("Promedio de cada fila:", convertir_2_decimales(calculo_prom_fila))

#6
#DAME LA MATRIZ FILTRADA DONDE EL PRIMER ELEMENTO DE CADA COLUMNA SEA MAYOR A 50
#Filtra las filas donde la columna 0 cumpla la condición
nueva_matriz = matriz[matriz[:, 0] > 50]
print("Filas donde el primer elemento es mayor a 50:",  convertir_2_decimales(nueva_matriz))

#7
matriz_transpuesta = matriz.T
print('Matriz transpuesta: ', convertir_2_decimales(matriz_transpuesta))



Array con 2 decimales: [  0.     1.69   3.39   5.08   6.78   8.47  10.17  11.86  13.56  15.25
  16.95  18.64  20.34  22.03  23.73  25.42  27.12  28.81  30.51  32.2
  33.9   35.59  37.29  38.98  40.68  42.37  44.07  45.76  47.46  49.15
  50.85  52.54  54.24  55.93  57.63  59.32  61.02  62.71  64.41  66.1
  67.8   69.49  71.19  72.88  74.58  76.27  77.97  79.66  81.36  83.05
  84.75  86.44  88.14  89.83  91.53  93.22  94.92  96.61  98.31 100.  ]
Matriz de 10 filas y 6 columnas: [[  0.     1.69   3.39   5.08   6.78   8.47]
 [ 10.17  11.86  13.56  15.25  16.95  18.64]
 [ 20.34  22.03  23.73  25.42  27.12  28.81]
 [ 30.51  32.2   33.9   35.59  37.29  38.98]
 [ 40.68  42.37  44.07  45.76  47.46  49.15]
 [ 50.85  52.54  54.24  55.93  57.63  59.32]
 [ 61.02  62.71  64.41  66.1   67.8   69.49]
 [ 71.19  72.88  74.58  76.27  77.97  79.66]
 [ 81.36  83.05  84.75  86.44  88.14  89.83]
 [ 91.53  93.22  94.92  96.61  98.31 100.  ]]
Promedio de cada columna: [45.76 47.46 49.15 50.85 52.54 54.24]
Prom

---
## Nivel Avanzado
> Preparan conceptos que usaras en las proximas semanas con Pandas.

### Pregunta 8 (15 pts): Mini Analisis Predictivo

Simula un dataset de 200 casas con las siguientes features:
- `area_m2`: uniforme entre 40 y 300
- `habitaciones`: enteros entre 1 y 6
- `antiguedad`: enteros entre 0 y 50 (anios)
- `precio` (target): calculado como `area_m2 * 1200 + habitaciones * 20000 - antiguedad * 500 + ruido`
  - donde `ruido = np.random.normal(0, 10000, 200)`

Luego:
1. Calcula estadisticos basicos de cada feature (media, std, min, max)
2. Calcula la correlacion de cada feature con el precio
3. Identifica cual feature tiene la mayor correlacion con el precio
4. Filtra las casas "baratas" (precio < mediana) y las "caras" (precio >= mediana)
5. Compara el area promedio de casas baratas vs caras

**Reflexion:** Que feature usarias para predecir el precio? Por que?

In [ ]:
import numpy as np

np.random.seed(42)

Primeras 5 casas del dataset
[[1.37380431e+02 4.00000000e+00 4.00000000e+00 2.51258229e+05]
 [2.87185720e+02 3.00000000e+00 1.10000000e+01 4.10456284e+05]
 [2.30318425e+02 1.00000000e+00 1.50000000e+01 2.83484656e+05]
 [1.95651206e+02 4.00000000e+00 2.50000000e+01 2.88081831e+05]
 [8.05648465e+01 6.00000000e+00 2.50000000e+01 1.95708478e+05]]
1. Estadisticos basicos
Area -> Media: 165.84, Std: 76.48, Min: 41.44, Max: 296.59
Habitaciones -> Media: 3.62, Std: 1.77, Min: 1.00, Max: 6.00
Antiguedad -> Media: 25.43, Std: 14.27, Min: 0.00, Max: 50.00
Precio -> Media: 259435.74, Std: 99683.99, Min: 48930.33, Max: 466771.24
2. Correlaciones con el precio
Correlacion Area-Precio: 0.9211
Correlacion Hab-Precio: 0.3556
Correlacion Antiguedad-Precio: -0.0501
3. Cual influye mas?
La feature que mas influye es: Area

4. La mediana del precio es: 244499.99
Casas baratas encontradas: 100
Casas caras encontradas: 100
5. Resultado del Analisis de Area
Promedio de area en casas baratas: 103.91 m2
Promedi

**Tu reflexion aqui:**

me fue interesante la tarea ya que refuerzo un lenguaje de programacion muy usado e interesante como lo es python, cada que iba avanzando la dificultad avanzaba ya se de logica o de tipear codigo.